# Changelog

All notable changes to this project will be documented in this file.

## [unreleased]

### 🚀 Features

- Init project
- 新增权重概略装配，根据数据字段rulevalues中是否有对应规则进行自动装配，且注意，该规则不影响概率表的装配。
- 新增抽奖行为规则过滤接口，分为抽奖前、中、后，尚未完善。

### 🐛 Bug Fixes

- 修复有mybatis动态代理机制引起的bean注入错误

<!-- generated by git-cliff -->
